# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded tdbo 0.1.4 [list source [file join $dir tdbo.tcl]]
package ifneeded tdbo::Itcl 0.1.0 [list source [file join $dir itcl.tcl]]
package ifneeded tdbo::Pgtcl 0.1.1 [list source [file join $dir pgtcl.tcl]]
package ifneeded tdbo::mysqltcl 0.1.1 [list source [file join $dir mysqltcl.tcl]]
package ifneeded tdbo::sqlite3 0.1.1 [list source [file join $dir sqlite3.tcl]]
package ifneeded tdbo::tdbc 0.1.0 [list source [file join $dir tdbc.tcl]]
package ifneeded tdbo::tdbc::mysql 0.1.0 [list source [file join $dir tdbc_mysql.tcl]]
package ifneeded tdbo::tdbc::postgres 0.1.0 [list source [file join $dir tdbc_postgres.tcl]]
package ifneeded tdbo::tdbc::sqlite3 0.1.0 [list source [file join $dir tdbc_sqlite3.tcl]]
